FROM almalinux:9
ENV Course = "Devsecops with AWS"\
    Trainer = "Shivakumar Reddy"\
    Containerization ="Docker"\
    Duration = "120hrs"
RUN echo "Hello ${ Trainer }" > /tmp/devops.txt
CMD ["sleep" , "100"]